
package service;

import javax.jws.WebMethod;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 *
 */
@WebService(name = "HelloService", targetNamespace = "http://127.0.0.1:7070/jdk")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface HelloService {


    /**
     *
     */
    @WebMethod
    public String sayHello();

}
